version: 0.2

env:
  exported-variables:
    - S3_BUCKET
  variables:
    CACHE_CONTROL: "86400"
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - node -v
      - npm install -g @angular/cli@16.1.2
  pre_build:
    commands:
      - npm install
      - echo "{\"hash\":\"$CODEBUILD_RESOLVED_SOURCE_VERSION\"}" > src/assets/commit-hash.json
  build:
    commands:
      - echo Building...
      - ng build --configuration production
      # - echo "User-agent\: \*\nDisallow: \/" > src/assets/commit-hash.json
  post_build:
    commands:
      - aws s3 sync ${BUILD_FOLDER} s3://${S3_BUCKET} --delete
      - echo S3 bucket is cleared.

artifacts:
  files:
    - "**/*"
  discard-path: no
  base-directory: ${BUILD_FOLDER}
