version: 0.2 

env:
   variables:
       CACHE_CONTROL: "86400"
       S3_BUCKET: "{{s3_bucket-url}}"
       BUILD_FOLDER: "dist"


phases:
 install:
   runtime-versions:
       nodejs: 18
   commands:
       - echo Installing source NPM dependencies...
       - npm config set legacy-peer-deps true
       - npm cache clean --force
       - npm install -g @angular/cli@latest
       - npm install
       - ng add @angular/material
       
 build:
   commands:
       - echo Build started
       - ng build
 
artifacts:
   files:
       - '**/*'
   base-directory: './dist*'
   discard-paths: yes
