version: 0.2 

env:
   variables:
       CACHE_CONTROL: '86400'
       S3_BUCKET: "{{s3_bucket-url}}"
       BUILD_FOLDER: 'dist'


phases:
 install:
   runtime-versions:
       nodejs: 14
   commands:
       - echo Installing source NPM dependencies...
	   - npm cache clean --force
       - npm install -g @angular/cli@latest
	   - npm install
       - npm add @angular/material
 build:
   commands:
       - echo Build started
       - ng build
 
artifacts:
   files:
       - '**/*'
   base-directory: './dist'
   discard-paths: yes
